Copystatic/admin/config.yml: copy code to clipboard
backend:
  name: github
  repo: vthacks-org/Live-Site
media_folder: static/assets
public_folder: /assets
collections:
  - name: schedule
    label: Schedule
    folder: content/schedule
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{name}}"
    extension: json
    fields:
      - { name: display, label: Display?, widget: boolean, default: true }
      - { name: name, label: Title, widget: string }
      - {
          name: subtitle,
          label: Event Leaders,
          widget: string,
          required: false,
        }
      - {
          name: start,
          label: Date,
          widget: datetime,
          date_format: "MM/DD/YYYY",
          time_format: "HH:mm",
          format: "MM/DD/YYYY h:mm a ZZ",
        }
      - {
          name: duration,
          label: Duration (In minutes),
          widget: number,
          value_type: int,
        }
      - {
          name: location,
          label: Location,
          widget: select,
          options:
            ["virtual", "main hall", "torg 1060", "torg 2150", "torg 1020", "torg 1040"],
        }
      - {
          name: category,
          label: Category,
          widget: select,
          options: ["workshop", "ux", "organizer", "sponsor"],
        }
      - { name: description, label: Description, widget: text, required: false }
      - { name: contentLink, label: Slides/VOD, widget: text, required: false }
      - { name: callLink, label: Stream Link, widget: text, required: false }
      - { name: prizes, label: Prizes, widget: text, required: false }

  - name: resources
    label: Resources
    folder: content/resources
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    extension: markdown
    format: frontmatter
    fields:
      - { name: display, label: Display?, widget: boolean, default: true }
      - { name: title, label: Title, widget: string }
      - {
          name: shouldDisplayTitle,
          label: "Display Title?",
          widget: boolean,
          default: true,
          hint: "If this field is set to true, the resulting markdown page will display the title field as a big header. Disable for more customization and control of the page",
        }
      - {
          name: "templateKey",
          label: "Template Key",
          widget: hidden,
          default: resources,
        }
      - { name: body, label: Body, widget: markdown }

  - name: prizes
    label: Prizes
    folder: content/prizes
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    extension: markdown
    format: frontmatter
    fields:
      - { name: display, label: Display?, widget: boolean, default: true }
      - { name: title, label: Title, widget: string }
      - {
          name: shouldDisplayTitle,
          label: "Display Title?",
          widget: boolean,
          default: true,
          hint: "If this field is set to true, the resulting markdown page will display the title field as a big header. Disable for more customization and control of the page",
        }
      - {
          name: "templateKey",
          label: "Template Key",
          widget: hidden,
          default: "prizes",
        }
      - { name: body, label: Body, widget: markdown }

  - name: submission_guidelines
    label: "Submission Guidelines"
    folder: content/submission-guidelines
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    extension: markdown
    format: frontmatter
    fields:
      - { name: display, label: Display?, widget: boolean, default: true }
      - { name: title, label: Title, widget: string }
      - {
          name: shouldDisplayTitle,
          label: "Display Title?",
          widget: boolean,
          default: true,
          hint: "If this field is set to true, the resulting markdown page will display the title field as a big header. Disable for more customization and control of the page",
        }
      - {
          name: "templateKey",
          label: "Template Key",
          widget: hidden,
          default: submission_guidelines,
        }
      - { name: body, label: Body, widget: markdown }
  - name: getting_started
    label: "Getting Started"
    folder: content/getting-started
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    extension: markdown
    format: frontmatter
    fields:
      - { name: display, label: Display?, widget: boolean, default: true }
      - { name: title, label: Title, widget: string }
      - {
          name: shouldDisplayTitle,
          label: "Display Title?",
          widget: boolean,
          default: true,
          hint: "If this field is set to true, the resulting markdown page will display the title field as a big header. Disable for more customization and control of the page",
        }
      - {
          name: "templateKey",
          label: "Template Key",
          widget: hidden,
          default: getting_started,
        }
      - { name: body, label: Body, widget: markdown }

  - name: sponsors
    label: Sponsors
    folder: content/sponsors
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    extension: markdown
    format: frontmatter
    fields:
      - { name: display, label: Display?, widget: boolean, default: true }
      - { name: title, label: Title, widget: string }
      - {
          name: shouldDisplayTitle,
          label: "Display Title?",
          widget: boolean,
          default: true,
          hint: "If this field is set to true, the resulting markdown page will display the title field as a big header. Disable for more customization and control of the page",
        }
      - {
          name: "templateKey",
          label: "Template Key",
          widget: hidden,
          default: sponsors,
        }
      - { name: body, label: Body, widget: markdown }

  - name: judges
    label: Judges
    folder: content/judges
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    extension: markdown
    format: frontmatter
    fields:
      - { name: display, label: Display?, widget: boolean, default: true }
      - { name: title, label: Title, widget: string }
      - {
          name: shouldDisplayTitle,
          label: "Display Title?",
          widget: boolean,
          default: true,
          hint: "If this field is set to true, the resulting markdown page will display the title field as a big header. Disable for more customization and control of the page",
        }
      - {
          name: "templateKey",
          label: "Template Key",
          widget: hidden,
          default: judges,
        }
      - { name: body, label: Body, widget: markdown }
