Copystatic/admin/config.yml: copy code to clipboard
backend:
  name: github
  repo: vthacks-org/Live-Site
media_folder: static/assets
public_folder: /assets
collections:
  - name: schedule
    label: Schedule
    folder: content/schedule
    create: true
    extension: json
    fields:
      - { name: name, label: Name, widget: string }
      - { name: start, label: Date, widget: datetime }
      - { name: duration, label: Duration, widget: number, value_type: int }
      - {
          name: category,
          label: Category,
          widget: select,
          options:
            [
              "default",
              "food",
              "workshop1",
              "workshop2",
              "activity",
              "career",
              "hacker",
            ],
        }
      - {
          name: location,
          label: Location,
          widget: select,
          options: ["Virtual", "Surge 301", "Surge 303"],
        }
      - { name: description, label: Description, widget: text }

  - name: resources
    label: Resources
    folder: content/resources
    create: true
    extension: markdown
    format: frontmatter
    fields:
      - { name: title, label: Title, widget: string }
      - { name: body, label: Body, widget: markdown }

  # - name: prizes
  #   label: Prizes
  #   folder: content/prizes
  #   create: true
  #   extension: markdown
  #   fields:
  #     - { name: name, label: Name, widget: string }
  #     - { name: description, label: Description, widget: markdown }

  # - name: submission_guidlines
  #   label: Submission Guidlines
  #   folder: content/submission_guidlines
  #   create: true
  #   extension: markdown
  #   fields:
  #     - { name: name, label: Name, widget: string }
  #     - { name: description, label: Description, widget: markdown }
